#!/usr/bin/env python3

import copy
import json
import time
import datetime
import optparse
import os
import string

from decimal import Decimal
import uuid


# Check that there is no product anymore that depends on this product
def product_dependencies_resolvable(invoice, code):
    for c, product in invoice.items():
        for dep in product.get('dependencies', []):
            if dep['id'] == code:
                return False
    return True

def resolve_invoice_dependencies(invoice):
    invoice = copy.deepcopy(invoice)
    changes = 1
    while changes > 0:
        changes = 0
        for code, product in invoice.items():
            if not product_dependencies_resolvable(invoice, code):
                continue
            for dependency in product.get('dependencies', []):
                changes += 1
                invoice[dependency['id']]['quantity'] += product['quantity'] * dependency.get('quantity', 1)
            invoice[code]["dependencies"] = []
    return invoice

def get_total_price(invoice):
    invoice = resolve_invoice_dependencies(invoice)
    total_price = Decimal(0)
    for code, product in invoice.items():
        billed_price = Decimal(str(product.get('price', 0))) * Decimal(str(product.get('quantity')))
        total_price += billed_price
    return total_price

def get_qif(invoice):
    qif = "!Type:Cash\n"
    qif += "T" + str(get_total_price(invoice)) + "\n"
    qif += "D" + time.strftime("%d") + "/" + time.strftime("%m") + "' " + time.strftime("%y") + "\n"
    qif += "MBierminister Verkauf\n"
    qif += "^"
    return qif

def get_invoice_ascii(invoice, width=60):
    invoice_string = ""
    invoice_string += "*" * width + "\n"
    invoice_string += "K1 Getränkeverkauf".center(width) + "\n"
    invoice_string += time.strftime("%d %b %Y %H:%M:%S").center(width) + "\n"
    invoice_string += ("ID: " + invoice_id).center(width) + "\n"
    invoice_string += "*" * width + "\n\n"

    for code, product in invoice.items():
        if product["quantity"] > 0:
            price = Decimal(str(product.get('price', 0)))
            billed_price = price * Decimal(str(product["quantity"]))
            billing_string = str(price).rjust(5) + \
                    str(" x " + str(product["quantity"])).rjust(6) + \
                    " = " + \
                    str(billed_price).rjust(6)

            name_string = product["name"].ljust(width - len(billing_string))
            invoice_string += name_string + billing_string + "\n"

    invoice_string += "-" * width + "\n"
    invoice_string += "Total:" + str(get_total_price(invoice)).rjust(width - 6) + "\n"

    return invoice_string

def get_entered_items_ascii(invoice):
    entered_items_string = ""
    for code, product in invoice.items():
        if product["quantity"] != 0:
            entered_items_string += str(product["quantity"]).rjust(4) + " x " + product["name"] + "\n"
    entered_items_string += "Total: " + str(get_total_price(invoice))
    return entered_items_string

def get_product_code(invoice, code):
    try:
        invoice[code]
        return code
    except KeyError:
        pass
    for codename, product in invoice.items():
        if code in product.get('alias', []):
            return codename
    return None

# add a --file argument and parse the arguments
parser = optparse.OptionParser()
parser.add_option("-f", "--file", dest = "filename", help = "load invoice from SOURCE", metavar = "SOURCE")
(options, args) = parser.parse_args()

# load an invoice from file or, if no file was given, use the default invoice prototype
if options.filename:
    invoice = json.load(open(options.filename))
else:
    invoice = json.load(open("invoice_prototype.olaf"))

print("Welcome to TurboOlaf!")

#TODO: Maybe make this unique...?
invoice_id = str(int(time.time()))

# set the quantity of all products to 0
#print(invoice)
for code, product in invoice.items():
    product["quantity"] = 0

previous_product_code = None
while True:
    entered = input("olaf > ")
    # clear immediately and then show the input again
    os.system("clear")
    print("olaf > " + entered)

    # end if an input was given
    if not entered:
        break
    else:
        if entered[0] == '$':
            # the input is a Sonderposten
            try:
                special_product = {}
                special_id = str(uuid.uuid4())
                invoice[special_id]['quantity'] = 1
                try:
                    special_name = entered[1:].split(' ')[1]
                except IndexError:
                    special_name = "Sonderposten"
                special_product['name'] = special_name
                special_product['price'] = Decimal(entered[1:].split(' ')[0])
                previous_product_code = special_id
                # only if nothing of the above failed, write the above
                invoice.update({
                    special_id: special_product
                    })
            except:
                print("Invalid Sonderposten format!")
        else:
            # the input is not a Sonderposten
            if entered[0] in string.ascii_letters:
                code = get_product_code(invoice, entered)
                # the input starts with a letter and will be followed by a product id
                if not code:
                    print("Invalid product code " + entered[1:] + " entered")
                else:
                    previous_product_code = code
                    print("Entered " + invoice[code]["name"])
                    invoice[code]["quantity"] += 1
            else:
                if len(entered) > 10:
                    # a code was scanned
                    for code, product in invoice.items():
                        if code == entered:
                            previous_product_code = code
                            print("Scanned " + invoice[code]["name"])
                            product["quantity"] += 1
                else:
                    # a quantity was entered
                    if previous_product_code:
                        try:
                            invoice[previous_product_code]["quantity"] += int(entered) - 1
                            print("Added another " + str(int(entered) - 1) + " " + invoice[previous_product_code]["name"])
                            previous_product_code = None
                        except ValueError:
                            print("No valid quantity entered")
                    else:
                        print("No previous product entered!")

        # finally, print a list of all scanned items
        print(get_entered_items_ascii(invoice))

print(get_invoice_ascii(resolve_invoice_dependencies(invoice)))

# TODO: write this out in a sorted manner e.g. yyyy/mm/dd/id.olaf
invoice_file = open("invoices/" + invoice_id + ".json", 'w')
invoice_file.write(json.dumps(invoice, indent=4))
invoice_file.close()

qif_file = open("qif/" + invoice_id + ".qif", 'w')
qif_file.write(get_qif(invoice))
qif_file.close()
